name: sts
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=23.1.0
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charset-normalizer=2.0.4
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - expat=2.5.0
  - fiona=1.9.1
  - folium=0.14.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.6.2
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.8.0
  - geotiff=1.7.0
  - giflib=5.2.1
  - glib=2.69.1
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.4
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgdal=3.6.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=12.15
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.10.4
  - libzip=1.8.0
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=2.1.1
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=3.1
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.0.11
  - packaging=23.1
  - pandas=2.1.1
  - pcre=8.45
  - pcre2=10.42
  - pillow=10.0.1
  - pip=23.3
  - pixman=0.40.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=6.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproj=2.6.1.post1
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - qhull=2020.2
  - readline=8.2
  - requests=2.31.0
  - rtree=1.0.1
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - setuptools=68.0.0
  - shapely=2.0.1
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tiledb=2.3.3
  - tk=8.6.12
  - tzdata=2023c
  - uriparser=0.9.7
  - urllib3=1.26.16
  - wheel=0.41.2
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.4.2
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
