name: get NRSC data

on:
  schedule:
    - cron: '35 0-23 * * *' #Runs at 35 minutes past the hour.
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  get-nrsc-data:
    runs-on: ubuntu-latest
    timeout-minutes: 19
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: env
          auto-activate-base: false
      - name: Cache Conda env
        uses: actions/cache@v3.3.2
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER
            }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache
      - name: Update environment
        run: conda env update -n env -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run script
        run: |
          python get_nrsc_data.py
          python v2/get_nrsc_data.py
      - name: Push new data
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add docs/*.json
          git add docs/v2/*.json
          git commit -m "Data update : $(date)"
          git status
          git push
